### ISSUE TITLE
Add ChargedParticle.dispose

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#109]
To support phet-io instrumentation, ChargedParticle must implement dispose.  I tried implementing this and ran into the problems identified in https://github.com/phetsims/phet-io/issues/319#issuecomment-257164312

I solved the problem by adding a synchronous disposeEmitter instead of allowing the model removal code to run before the view removal code (which was causing the error in Property.dispose because the view was still observing the model.)  Tests look like this works properly, and now the state wrapper works as well (with the phet-io branch identified in the issue linked above).

Committing shortly.

**Comment by samreid** [comment]
Changed pushed above.  Lint is passing.  Tests in chrome seem good, I can create particles and put them back in the toolbox.  Reset is working.  It works in the states wrapper in the phet-io branch.  @andrewadare can you please review the changes?

**Comment by andrewadare** [comment]
@samreid code changes look good and fuzz test in browser passes without problems.
