### ISSUE TITLE
branch: webgl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/charges-and-fields#11]
Please describe this branch and plans for it.

**Comment by veillette** [comment]
The webgl branch was merged into master. It is no longer necessary. Deleting. Closing

**Comment by jonathanolson** [comment]
Using this branch, republished. Need to do additional work for iPad compatibility.

**Comment by veillette** [comment]
@jonathanolson can we delete this branch (webgl) at this point?

**Comment by jonathanolson** [comment]
Yup, removed it.
