### ISSUE TITLE
Electric Potential Sensor grabbed at different points

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#128]
Mirror inputs for http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.1.0-phetiodev.1/wrappers/mirror-inputs/mirror-inputs.html?sim=charges-and-fields&relativeSimPath has issues with the electric potential sensor. When grabbing it from the tool box, the "pick up point" is the crosshairs (the crosshairs jump underneath the cursor). This does not happen in the below sim where the little draggy thumb at the bottom of the sensor is the pick up point:

![cafio04](https://user-images.githubusercontent.com/5863899/29578710-7a6762e6-872d-11e7-8155-ccee25766261.gif)

Some things to note:
- The tape measurer does not get out of sync in this way.
- The potential sensor tool has the pick up point naturally (in all wrappers, not just mirror inputs)
- Current master of BOTH brands does not have this pick up point. The tool is grabbed at the thumb on master.

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/37

**Comment by samreid** [comment]
This code appears in ElectricFieldSensorNode.js

```js
            if ( event.pointer.isTouch ) {
              globalPoint.addXY( 0, -2 * ChargesAndFieldsConstants.ELECTRIC_FIELD_SENSOR_CIRCLE_RADIUS );
            }
```

There is similar code in ChargedParticleNode.js

```js
            if ( event.pointer.isTouch ) {
              globalPoint.addXY( 0, -2 * CIRCLE_RADIUS );
            }
```

**Comment by samreid** [comment]
False alarm, the sensor is called ElectricPotentialSensorNode, not ElectricFieldSensorNode

**Comment by samreid** [comment]
If I add this console.log at the top of ChargesAndFieldsToolboxPanel.js

```js
  var SENSOR_HEIGHT = electricPotentialPanelOutlineImage.height;
  console.log(SENSOR_HEIGHT);
```

I can see that the recording sim is loading with height 0 and the playback sim is loading with height 535.  Since the vertical offset is set by this image height, it creates the discrepancy:

```js
var initialViewPosition = self.globalToParentPoint( event.pointer.point ).plusXY( 0, -SENSOR_HEIGHT * 6 / 25 );
```

**Comment by phet-steele** [comment]
Looks fixed in http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.1.0-phetiodev.3/wrappers/mirror-inputs/mirror-inputs.html?sim=charges-and-fields&relativeSimPath. Thanks @samreid.
