### ISSUE TITLE
Crosshair mount is incorrect

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#129]
Look at the little rectangle that connects the crosshair to the body. In published:

<img width="120" alt="screen shot 2017-08-22 at 12 56 58 pm" src="https://user-images.githubusercontent.com/5863899/29582382-b8fe0ea4-8739-11e7-892c-1db413b08ab7.png">

But on master and in phetsims/QA/issues/37, it's a circle:
<img width="148" alt="screen shot 2017-08-22 at 12 56 51 pm" src="https://user-images.githubusercontent.com/5863899/29582381-b8fdd8a8-8739-11e7-947d-cdc4795ea168.png">

The mount is correct once it is dragged out from the toolbox. Seen on macOs 10.12.6 Chrome.

**Comment by jonathanolson** [comment]
It looks like this may have been purposely added in https://github.com/phetsims/charges-and-fields/commit/f412cc081c3cbe68c933b5c9623bc1ee4dd85c0e#diff-9106056b55c9f988721c00e7e8a04136 (would be hard to accidentally add two different corner radii parameters without meaning to?)

![caf-bit](https://user-images.githubusercontent.com/480878/29586241-3762bc38-8747-11e7-901b-226277394561.PNG)

Is it for-sure a bug?

**Comment by phet-steele** [comment]
Let's investigate!

**Comment by phet-steele** [comment]
@jonathanolson it is not supposed to be there. I can't find documentation on github and @arouinfar also said it "doesn't need to be a dot".

**Comment by jonathanolson** [comment]
Ok, should be fixed now.

**Comment by phet-steele** [comment]
Beautiful.
