### ISSUE TITLE
Electric lines are removed when snapping doesn't change anything

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#132]
Test device: MacBook Pro 2015

Operating System: macOS 10.12.6

Browser: Chrome 60.0.3112.101 (Official Build) (64-bit)

Problem description:
From the changes in #98, we now have a "Snap to Grid" feature. This feature moves the charges to a grid location when you select it. This is problematic in cases where every charge is ALREADY in a grid location. Selecting Snap to Grid still technically "sets" the position of a charge, even if it would be unnecessary. This causes electric field lines to disappear even when the play area has not been changed (ie. moving/placing charges). @arouinfar, is this desired behaviour?  For phetsims/QA/issues/37 sort of, this is off master.

Steps to reproduce:
1. Drag out some charges
2. Select Snap to Grid. This ensures the charges are on a grid location for later steps.
3. Deselect Snap to Grid
4. Draw some electric potential lines
5. Select Snap to Grid again. Your lines are gone, but nothing changed! 😢 

Charges do not move when I select Snap to Grid in this video:
![caf09](https://user-images.githubusercontent.com/5863899/29630606-014a022e-87fa-11e7-908b-74c4feb344c2.gif)

Troubleshooting information (do not edit):
Name: ‪Charges And Fields‬
URL: http://phettest.colorado.edu/charges-and-fields/build/charges-and-fields_en.html
Version: 1.1.0-dev.1 2017-08-22 19:38:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"62935a11","branch":"master"},"babel":{"sha":"f29b96d0","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"charges-and-fields":{"sha":"e84bfa92","branch":"master"},"chipper":{"sha":"157b6f57","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"efdda1ba","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"6bfeef5c","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"d539ecd7","branch":"master"},"scenery-phet":{"sha":"ae0e06ea","branch":"master"},"sherpa":{"sha":"dba01386","branch":"master"},"sun":{"sha":"50f640e7","branch":"master"},"tandem":{"sha":"e6a58f1e","branch":"master"}}

**Comment by arouinfar** [comment]
No, not the desired behavior @phet-steele. If the charges are already snapped to the grid, then the electric potential lines should not erase when toggling Snap to Grid.

**Comment by arouinfar** [comment]
@phet-steele says @jonathanolson is shepherding the sim, so reassigning.

**Comment by samreid** [comment]
Proposed fix is committed above, @phet-steele let me know if you'd like a new dev version or if you'll be testing this on phettest.

**Comment by phet-steele** [comment]
Fixed for me @samreid! You can just assume I use phettest always.
