### ISSUE TITLE
User suggestion: measure should snap to lattice points

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/charges-and-fields#134]
> There is no problem but I just wanted to say that when you drag the things onto the screen they should "snap" to the grid lines. As in the dots should immediatley move to a lattice point when you let go of the mouse.

This may be a necessary feature for future keyboard navigation of the sim.

**Comment by arouinfar** [comment]
@oliver-phet this change is already in progress. See https://github.com/phetsims/charges-and-fields/issues/98. Not sure what the timeline is to redeploy the sim, but maybe @ariel-phet or @phet-steele would know?

**Comment by phet-steele** [comment]
It is currently being tested for a general purpose phet/phet-io release! But I cannot speak to its priority with upcoming CCK shenanigans and/or if testing could be finished before CCK is ready for testing.

**Comment by ariel-phet** [comment]
@arouinfar I think after CCK and likely after Capacitor Lab Basics would be the timeline, marking as deferred for the moment. Since JO is the one that will likely redeploy CL:B will be higher in priority.

**Comment by arouinfar** [comment]
Thanks @ariel-phet.

@oliver-phet can you respond to the user? We're tracking this change in #98, so we can close this issue once the user has been responded to.

**Comment by oliver-phet** [comment]
Email to user sent. Closing.

**Comment by arouinfar** [comment]
Thanks @oliver-phet!
