### ISSUE TITLE
White tape measure text on white E field arrow

### ISSUE THREAD

**Issue by ghost** [phetsims/charges-and-fields#139]
This is quite nit-picky, but it's difficult to read the length on the tape measure if its text is on top of an E field arrow.

![screen shot 2017-09-07 at 11 22 55 am](https://user-images.githubusercontent.com/31285590/30176336-4ca75318-93bf-11e7-9ec1-f8e30fcfecc4.png)

**Comment by arouinfar** [comment]
Thanks @lmulhall-phet! Agreed that occlusion is not ideal.

@phet-steele I think we ran into a similar issue for Projectile Motion. Did we discuss the possibility of adding a shaded rectangle behind the readout? Perhaps that wasn't supported in the tapeMeasure node...

**Comment by phet-steele** [comment]
I also can't remember! @pixelzoom, does the tape measure support adding a shaded rectangle behind its readout?

**Comment by pixelzoom** [comment]
The tape measure is implemented in scenery-phet `MeasuringTapeNode`.  I see no option for adding a shaded rectangle behind the value readout.  A quick look suggests that it wouldn't be too difficult to add.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I opened an issue in scenery-phet (linked above) to discuss this addition to `MeasuringTapeNode`.

**Comment by pixelzoom** [comment]
I integrated the new "transparent rectangle behind readout" feature into this sim.  Sample screenshot below.  The rectangle color is currently `'rgba( 0, 0, 0, 0.65 )'` - black with 65% transparency.  @arouinfar please review in master, let me know if you'd like anything changed.

![screenshot_403](https://user-images.githubusercontent.com/3046552/31145112-0e706da6-a840-11e7-9e45-6fd0e211ada5.png)

**Comment by pixelzoom** [comment]
I'm going to wait until @arouinfar has reviewed sim changes (https://github.com/phetsims/charges-and-fields/issues/139, https://github.com/phetsims/projectile-motion/issues/156) before I assign this to be reviewed.

**Comment by arouinfar** [comment]
Looks great @pixelzoom!

**Comment by pixelzoom** [comment]
Great. Closing.
