### ISSUE TITLE
[Measuring Tape]: setting ModelViewTransform should update base and tip position

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#14]
I haven't gotten a chance to look at the actual code yet, but I am seeing some buggy behavior in GAO when setting the MVT.

Pull from GAO master and go to screen 2. Add the tape, and then adjust the scale slider in the top right. Then move the tape. The tape will "jump" all of a sudden to the new location as determined by the MVT.

I think setting the MVT should update the position of the base and the tail.

**Comment by aaronsamuel137** [comment]
Related to code review #13

**Comment by aaronsamuel137** [comment]
Also, once we verify that updating the MVT scales the tape properly in GAO, we can get rid of "scaleProperty". This was needed in the old MLL version of GAO, but not in the new direct port.

**Comment by veillette** [comment]
Setting the modelviewTransform  calls an update function on the measuringTape. I also deleted the scaleProperty. Assigning to @aaronsamuel137  for a review

**Comment by aaronsamuel137** [comment]
Looks great! Closing
