### ISSUE TITLE
User suggestion: toggle additional units

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/charges-and-fields#143]
> It would be great to have the option of toggling the units on Charges and Fields between
> V/m and N/C.
> Perhaps under the Options menu choice.

Assigning to @arouinfar to decide.

**Comment by arouinfar** [comment]
I can understand the teacher's motivation for wanting to use N/C. Expressing the electric field in units of N/C is useful when thinking about the electric field as E=F/q, while units of V/m parallel E=V/r.  

If we allow for E to be expressed as N/C, it's a bit hard to make a connection between the electric field (N/C) and the equipotentials (V). For consistency, we should probably express V as Nm/C. However, this would make things a bit messy, particularly in the equipotential tool. 

I'm inclined to pass on this suggestion. What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar I think I agree. V/m and N/C are exactly the same "fundamental" units in terms of mks, and changing those units would not alter the value or anything. So it seems a very minor learning goal, and not well tied to the sim. 

If we did have this option, I would only change the units of the field. But I think we will pass.

@oliver-phet please let the teacher know that we appreciate and undrerstand the suggestion, but considering that this sim is focused on the relationship between the equipotential mapping and the electric field, we have decided to keep only one form of the units.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.
