### ISSUE TITLE
Regression on Master regarding position of the equipotential tool.

### ISSUE THREAD

**Issue by veillette** [phetsims/charges-and-fields#146]
While working on #98, i noticed that the equipotential sensor tool moves to the upper left corner of the dev bounds when one attempts to grab it from the toolbox.

**Comment by jonathanolson** [comment]
Probably DragListener regression, I'll look into it.

**Comment by jonathanolson** [comment]
I believe I've fixed this with the above commit. @veillette can you verify?

**Comment by veillette** [comment]
Thanks @jonathanolson , this does indeed fix it. Closing
