### ISSUE TITLE
[Measuring Tape] Commented code

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#16]
During code review #13 for the measuring tape, I noticed this commented line:

``` js
    //this.tipPositionProperty = new Property( options.basePositionProperty.value.plus( Vector2.createPolar( options.unrolledTapeDistance, options.angle ) ) );
```

I wanted to check with you before deleting it, in case it is there as a reminder to you for something.

**Comment by veillette** [comment]
I deleted that line of code but I tagged the wrong issue. Closing
