### ISSUE TITLE
[Measuring Tape] possible confusion with scenery options

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#17]
During code review #13, I noticed that measuring tape calls `this.mutate( options )`.

I think this is potentially useful, but also could be confusing. If you set x, y, etc. the entire bounds with the measuring tape are positioned. Perhaps there should be an assert if these are set? Or maybe we should just warn in the documenting that position should be set with basePositionProperty instead of scenery options. Or both? Do you have any thoughts on which of these you'd prefer @bereaphysics?

**Comment by veillette** [comment]
This looks like a similar issue with the scenery phet measuring tape, https://github.com/phetsims/scenery-phet/issues/126

Indeed you don't want to set x and y in this manner. I'm not sure on the upside of having mutate(options). At the very least we should put documentation about the proper way to position the measuringTape.

**Comment by veillette** [comment]
The documentation was added.
