### ISSUE TITLE
Refactor of hasMagneticField

### ISSUE THREAD

**Issue by veillette** [phetsims/charges-and-fields#172]
While commenting on #171, I noticed that
````
   const hasMagneticField = this.model.getElectricField( position ).magnitude !== 0;
````
It would be more useful to rename this variable as hasElectricField.

**Comment by veillette** [comment]
Assigning to @samreid  since he has made of lot of recent commits as part of Phet-IO on this simulation.

**Comment by samreid** [comment]
Thanks @veillette, I'll take a look.

**Comment by samreid** [comment]
Fixed, closing.
