### ISSUE TITLE
Unable to drag multiple of the same draggable particles at once

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#18]
1. Drag and hold a charge over the play area, don't let go!!
2. While still holding the charge press the reset all button with another finger.
3. Still don't let go! Now trying to drag out another charge of the same type you began with is not possible. Works with sensors, too.

Additionally, if you don't proceed to step two, you still can't drag out multiple things anyway.

Tested in 1.0.0-dev.9

**Comment by veillette** [comment]
We need a createDragHandler function. There is currently only one dragHandler per particle.

**Comment by veillette** [comment]
Addressed in https://github.com/phetsims/charges-and-fields/commit/42d613a018e55fe8617b4703caf2c372e9d70319

Closing
