### ISSUE TITLE
Electrostatic potential colors not visible Safari 14

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/charges-and-fields#189]
I think this might be done in WebGL... wondering if something changed in Safari 14 that caused this? @arouinfar Do you experience this behavior on your mac (if you've updated to latest)?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5090275/93651442-b5fc2000-f9ce-11ea-89c0-26d597ddb82d.png">
Name: ‪Charges and Fields‬
URL: https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_en.html
Version: 1.0.47 2020-08-02 08:36:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Language: en-us
Window: 1680x987
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"e8a10b55","branch":"master"},"brand":{"sha":"e4981a6a","branch":"HEAD"},"charges-and-fields":{"sha":"797dc613","branch":"HEAD"},"chipper":{"sha":"b5faea63","branch":"HEAD"},"dot":{"sha":"3f60cfcc","branch":"HEAD"},"joist":{"sha":"57af1e31","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"phet-core":{"sha":"bebc92b7","branch":"HEAD"},"phetcommon":{"sha":"a4865924","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"1802fce2","branch":"HEAD"},"scenery-phet":{"sha":"4608a681","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"4b852127","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by arouinfar** [comment]
I am on macOS 10.15.6 (latest). In Safari 13.1.2 the electrostatic potential shows up (screenshot below). Updating to Safari 14 breaks it.
![image](https://user-images.githubusercontent.com/8419308/93658664-e78ae080-f9fa-11ea-9f45-56b18d3322bb.png)

**Safari 13**
Name: ‪Charges and Fields‬
URL: https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_en.html
Version: 1.0.47 2020-08-02 08:36:22 UTC
Features missing: csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Language: en
Window: 1694x984
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"e8a10b55","branch":"master"},"brand":{"sha":"e4981a6a","branch":"HEAD"},"charges-and-fields":{"sha":"797dc613","branch":"HEAD"},"chipper":{"sha":"b5faea63","branch":"HEAD"},"dot":{"sha":"3f60cfcc","branch":"HEAD"},"joist":{"sha":"57af1e31","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"phet-core":{"sha":"bebc92b7","branch":"HEAD"},"phetcommon":{"sha":"a4865924","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"1802fce2","branch":"HEAD"},"scenery-phet":{"sha":"4608a681","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"4b852127","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Safari 14**
Name: ‪Charges and Fields‬
URL: https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_en.html
Version: 1.0.47 2020-08-02 08:36:22 UTC
Features missing: csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Language: en-us
Window: 1272x800
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"e8a10b55","branch":"master"},"brand":{"sha":"e4981a6a","branch":"HEAD"},"charges-and-fields":{"sha":"797dc613","branch":"HEAD"},"chipper":{"sha":"b5faea63","branch":"HEAD"},"dot":{"sha":"3f60cfcc","branch":"HEAD"},"joist":{"sha":"57af1e31","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"phet-core":{"sha":"bebc92b7","branch":"HEAD"},"phetcommon":{"sha":"a4865924","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"1802fce2","branch":"HEAD"},"scenery-phet":{"sha":"4608a681","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"4b852127","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by arouinfar** [comment]
It doesn't seem like a general webGL problem, however. Molecule Shapes looks fine in Safari 14.
![image](https://user-images.githubusercontent.com/8419308/93658845-806e2b80-f9fc-11ea-9a09-0565d51e3783.png)

**Comment by arouinfar** [comment]
Assigning to the responsible dev, @jonathanolson.

**Comment by KatieWoe** [comment]
I thought I had checked this in Beta. I must have missed it, sorry about that.

**Comment by ariel-phet** [comment]
Fix has been deployed. Closing
