### ISSUE TITLE
Invisible particles

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#19]
1. Drag and drop a particle on the play area.
2. Pick it back up and don't release it, ever.
3. Press the reset all button with another finger.
4. Pick up another particle and drop it in the play area (remember you're still holding the particle from step one, don't let go!).
5. Move your original finger around (from step 2) and then you'll have an invisible particle.

Tested on 1.0.0-dev.9

**Comment by veillette** [comment]
This happens on all the platform. This is not an invisible particle though. It only affects the electric field. It is the result of calculating the electric field through delta contributions. You can clearly see that you have created a dipole moment in this fashion.

**Comment by veillette** [comment]
Reset the grids to zero will address this issue. Closing
