### ISSUE TITLE
Blocky voltage, particularly for negative charge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#190]
**Test device**
MacBook Air
**Operating System**
Mac 10.15.7
**Browser**
Safari 14.0
**Problem description**
For https://github.com/phetsims/QA/issues/559.
I noticed that the voltage colorization was blockier on Safari 14 then I expected. The blockiness seemed particularly noticeable with the blue negative voltage. Did not see this in Chrome on the same device.

**Visuals**
![Screen Shot 2020-10-13 at 10 29 19 AM](https://user-images.githubusercontent.com/41024075/95892334-9ba23180-0d43-11eb-9ef7-58e6b87f9937.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Charges and Fields‬
URL: https://phet-dev.colorado.edu/html/charges-and-fields/1.0.48-rc.1/charges-and-fields_all.html
Version: 1.0.48-rc.1 2020-10-01 19:33:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Language: en-us
Window: 1313x734
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"d69aa800","branch":"master"},"brand":{"sha":"e4981a6a","branch":"HEAD"},"charges-and-fields":{"sha":"610fef38","branch":"HEAD"},"chipper":{"sha":"b5faea63","branch":"HEAD"},"dot":{"sha":"3f60cfcc","branch":"HEAD"},"joist":{"sha":"57af1e31","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"phet-core":{"sha":"bebc92b7","branch":"HEAD"},"phetcommon":{"sha":"a4865924","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"1802fce2","branch":"HEAD"},"scenery-phet":{"sha":"4608a681","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"4b852127","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
Interestingly enough, it looks better in screenshots taken with the phet menu

**Comment by jonathanolson** [comment]
This is a consequence of the workaround for Safari 14. @ariel-phet, how much time would it be worth to investigate trying to get the higher-quality one working? (Already spent about 2 hours)

**Comment by ariel-phet** [comment]
@jonathanolson @KatieWoe the presentation of voltage is acceptable, especially since this visualization is for giving a qualitative feel and the "blockiness" observed is not problematic in my opinion.

Closing as `wontfix`
