### ISSUE TITLE
User request: support 3D visualization 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/charges-and-fields#193]
suggestion from gmelo@elpoli.edu.co

He uses the simulation to apply Gauss's Law.  He suggests making the sim more useful for this by allowing to rotate the view and see the changes in a 3D view. In his university, they have a lab activity where they use a cylindrical closed surface to apply Gauss's Law, So it is not obvious to your students which surface shape to use in the simulation for their calculations. Initially, they used a cylinder, but finding errors, they used a sphere. This happens year after year. It is not obvious to students that the charges in the simulation are spherical. So he suggests that moving the 3D viewing angle would make it easier for students to understand. 

He includes in his email the link to this other resource: https://www.falstad.com/vector3de/ as an example of how the 3D rotation can be visualized: 

![image](https://user-images.githubusercontent.com/26031501/116725043-0d239380-a9a7-11eb-8193-c62f98154ccf.png)

**Comment by arouinfar** [comment]
Thanks for sharing this suggestion with us @DianaTavares.

We use a 2D model, and rewriting it to support 3D visualization would be costly. The user's goals go beyond the scope of the learning goals for the sim, so I don't think this would be a feature we would add support for. Closing.
