### ISSUE TITLE
Delete PhET-iO version 50

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#198]
In Slack, @kathy-phet said:

When I was looking into the "Launch" issue, I came across the fact that Charges and Fields is entirely broken, because somehow it looks like the 1.0.50 MR of the main sim, leaked into the phet-io directory ... From MR https://github.com/phetsims/qa/issues/708 there were 3 CAF sims tested:
charges-and-fields 1.0 (phetsims/chipper#1080, phetsims/chipper#1093)
 charges-and-fields 1.0.50-rc.1
charges-and-fields 1.0-phetio (phetsims/chipper#1080, phetsims/chipper#1093)
 charges-and-fields 1.0.22-rc.1 phet-io
 charges-and-fields 1.0.22-rc.1 phet-io Instance Proxies
But phet-io has a 1.0.50 directory, and it doesn't have all of its directory pieces. So the redirect is taking us to that directory, and it doesn't work at all (blank). Can we just delete the 1.0.50 directory from the phet-io server, since it wasn't supposed to be there?
Here is a list of all of the directories in charges-and-fields phet-io:
sims/charges-and-fields:
1.0.0-phetio
1.0.12-phetio
1.0.13-phetio
1.0.14-phetio
1.0.15-phetio
1.0.16-phetio
1.0.17-phetio
1.0.18-phetio
1.0.19-phetio
1.0.1-phetio
1.0.20-phetio
1.0.21-phetio
1.0.22-phetio
1.0.50-phetio
1.0.7-phetio
1.0.8-phetio
(Matt P got these for me)

**Comment by samreid** [comment]
@kathy-phet said:

> We would need to change the version on this as well .. https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminPhetioDeploy

**Comment by kathy-phet** [comment]
Closing. We hope the next MR will fix this. And we discovered the source issue within the translation deployment code. JB and LM are fixing that.
