### ISSUE TITLE
Equipotential Sensor behavior when placed on top of charges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#2]
The equipotential lines that are drawn when the sensor is placed on top of a charge look strange. If two charges are placed on top of another, the sim will crash or the UI will disappear. The flash version has the strange line issue but not the crashing one.
![chafi](https://cloud.githubusercontent.com/assets/5863899/6307810/37eaf6be-b8fc-11e4-901d-1d4ed555b6eb.gif)

Tested on Win 8.1 and iOS 8 in 1.0.0-dev.3
Troubleshooting information:
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.3/charges-and-fields_en.html
Version: 1.0.0-dev.3
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1920x1063
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by veillette** [comment]
This is related to issue #5. The crash is being prevented by not pushing an equipotentialLine to the observable array when the line is null. The broken line issue is addressed in #5.
