### ISSUE TITLE
charges-and-fields-colors.html is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/charges-and-fields#21]
charges-and-fields-colors.html is broken, console error message:

> Uncaught TypeError: charges-and-fields-colors.html:90 Uncaught TypeError: 
> Cannot set property 'value' of null

Noticed this while working on https://github.com/phetsims/sun/issues/171, which involved removing ChargedAndFieldsColors.controlPanelTextDisabled and checkBoxDisabled. I thought I might have broken something, but reverted my changes and the problem persisted. 

Recommend to either fix this or delete charges-and-fields-colors.html.

**Comment by veillette** [comment]
thanks @pixelzoom. I removed the unnecessary colors. Closing
