### ISSUE TITLE
Crossing equipotenials

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#24]
@bereaphysics is aware of this issue, I'm making this for reference to the setup.

![screen shot 2015-05-01 at 12 57 25 pm](https://cloud.githubusercontent.com/assets/5863899/7435607/31f123c2-f002-11e4-8eaf-82576bead76f.png)

![screen shot 2015-05-01 at 1 02 07 pm](https://cloud.githubusercontent.com/assets/5863899/7435621/51de031c-f002-11e4-8142-f3f6275612d4.png)

![screen shot 2015-05-01 at 1 04 13 pm](https://cloud.githubusercontent.com/assets/5863899/7435652/a5db5bb8-f002-11e4-9467-340a7373ba1d.png)

Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.11/charges-and-fields_en.html
Version: 1.0.0-dev.11
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25
Language: en-us
Window: 1217x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.19)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by ariel-phet** [comment]
@phet-steele it might be good to know if this exists in the original flash sim

**Comment by phet-steele** [comment]
I couldn't with the above setup. I honestly didn't expect this to occur in the flash since @bereaphysics mentioned before I found this that he had changed the way the lines are drawn and warned me something like this would happen, so of course I had to make it happen. I think it's just something he changed in the HTML5 code himself.

**Comment by veillette** [comment]
This has been addressed in the new drawing algorithm. it is not as fast as before but it will prevent this kind of situation. good finding @phet-steele . closing
