### ISSUE TITLE
User suggestions for Charges and Fields

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/charges-and-fields#25]
1.  It would be great if the electric field arrows were evaluated and displayed on the intersections of the grid.
   This way if you put a charge on an intersection and looked at the field directly above it would point directly away.
   (see screenshot).
2. It would be nice to be able to save a particular configuration.  Even if just the locations of the particle were saved.  Saving the settings “grid on” or “Efield” is not as important.

**Comment by ariel-phet** [comment]
Suggestion (1) has already been implemented in the HTML5 version

Suggestion (2) is a bit more complicated and especially with the alignment of the field and grid, it will be easy to recreate certain patterns. As Save and Load features of sims become more possible this may not require a special addition to the sim.

**Comment by ariel-phet** [comment]
Since we have addressed (1) - we will currently punt on (2) as we hope such possibilities will exist for all sims in the future with our interoperable goals.
