### ISSUE TITLE
console.log and TODO in ElectricPotentialSensorNode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#29]
I noticed this when running the fuzz tester. The TODO says to get rid of the timing - should this be done now, or is it still needed? Is the console.log still needed?

See code review #28.

**Comment by veillette** [comment]
Unless there is a performance issue in the release candidate this wont be needed. Console.log and TODO are removed. Assigning to @aaronsamuel137  for review.

**Comment by aaronsamuel137** [comment]
Looks good. Closing.
