### ISSUE TITLE
Missing assets/*-screenshot.png

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#30]
Needs a screen shot checked in under assets. Should be 2048x1344, PNG, 32-bit color with the browser chrome chopped off.

**Comment by veillette** [comment]
@arouinfar : I am going to ask you to do the screenshot. You can use the most recent dev version. I can check the screenshot in if you don't know how.

**Comment by arouinfar** [comment]
Screenshot has been created and emailed to @bereaphysics to check in.

**Comment by veillette** [comment]
The screenshot has been checked in. It has the requested size and filetype. Assigning to @aaronsamuel137 for review

**Comment by aaronsamuel137** [comment]
Looks good. Closing
