### ISSUE TITLE
dev query param does nothing

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#33]
In code review #28, I noticed that the dev param code is still identical to the simula-rasa template, and does nothing:

``` js
// Appending '?dev' to the URL will enable developer-only features.
  if ( phet.chipper.getQueryParameter( 'dev' ) ) {
    simOptions = _.extend( {
      // add dev-specific options here
    }, simOptions );
  }
```

Not sure what our convention is here. Leave this in case we want it later, or just take it out all together. Any other developers have thoughts on this?

**Comment by samreid** [comment]
I'd recommend to delete this from simula-rasa and from all sims where it is a no-op.

**Comment by aaronsamuel137** [comment]
Deleted from CAF. We can make a separate issue for simula-rasa if that seems useful. Closing here.
