### ISSUE TITLE
constrainLocation code duplicated

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/charges-and-fields#39]
During code review #28, I noticed the constrainLocation code duplicated twice (once in UserCreatorNode and once in ChargesAndFieldsToolboxPanel). It also occurs in MovableDragHandler, which I believe is where it was copied from.

``` js
  var constrainLocation = function( location, bounds ) {
    if ( bounds.containsCoordinates( location.x, location.y ) ) {
      return location;
    }
    else {
      var xConstrained = Math.max( Math.min( location.x, bounds.maxX ), bounds.x );
      var yConstrained = Math.max( Math.min( location.y, bounds.maxY ), bounds.y );
      return new Vector2( xConstrained, yConstrained );
    }
  };
```

Perhaps this should be moved to common code somewhere? Maybe DOT.Uitl? Any thoughts on this @pixelzoom?

**Comment by pixelzoom** [comment]
A few options...

Add instance functions to Bounds2:

```
constrainPoint( {Vector2} point ); // @returns {Vector2}
constrainXY( {number} x, {number} y ); // @returns {Vector2} 
constrainX( {number} x ); // @returns {number}
constrainY( {number} y ); // @returns {number
```

Add instance function to Vector2:

```
constrainToBounds( {Bounds2} bounds ); // @returns {Vector2}
```

Add static functions to DOT.Util:

```
constrainPointToBounds( {Vector2} point, {Bounds2} bounds ); // @returns {Vector2}
constrainXYToBounds( {number} x, {number} y, {Bounds2} bounds ); // @returns {Vector2}
constrainXToBounds( {number} x, {Bounds2} bounds ); // @returns {number}
constrainYToBounds( {number} y, {Bounds2} bounds ); // @returns {number}
```

Adding to Bounds2 is most similar to other 'constrain' functions in Bounds2, and Range.constrainValue. I like the static functions in DOT.Util the least.

Get @jonathanolson's opinion too.

**Comment by aaronsamuel137** [comment]
Adding to Bounds2 seems like a good way to go to me. Do you have any thoughts @jonathanolson?

**Comment by jonathanolson** [comment]
As noted in https://github.com/phetsims/dot/issues/28, I'd prefer bounds.closestPointTo( ... ) if it will be in dot. Constrain to me doesn't describe which point is chosen.

**Comment by aaronsamuel137** [comment]
Sounds like Bounds2 is the preferred location for this. Any objections to adding closestPointTo to Bounds2 @pixelzoom? If not, I'll go ahead and add this method.

**Comment by pixelzoom** [comment]
Sounds good. 

@jonathanolson Do you think we should change Range.constrainValue to Range.closestValueTo? Or something else?

**Comment by jonathanolson** [comment]
I'd prefer closestValueTo, since it seems more descriptive.

**Comment by jonathanolson** [comment]
Also, to me 'constrain' sounds more like a mutable operation, where if you x.constrain( y ), now y has been constrained.

**Comment by aaronsamuel137** [comment]
added closestPointTo and removed constrainBounds from CAF files as well as movableDragHandler. Looks like constrainBounds has also been copied into Bending Light and used all over that sim. Made an issue there to replace with closestPointTo eventually: https://github.com/phetsims/bending-light/issues/49.

Feel free to review and close if you'd like @jonathanolson or @pixelzoom.

**Comment by jonathanolson** [comment]
Looks good to me.
