### ISSUE TITLE
No boundary for objects

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/charges-and-fields#4]
Observed on all platforms.
Objects (Charges, Sensors, Equipotential meter) can all be moved off screen, and also moved out of the defined region for the vector field.

Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.3/charges-and-fields_en.html
Version: 1.0.0-dev.3
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.53 Safari/537.36
Language: en-us
Window: 1366x681
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by veillette** [comment]
all the tools and movable elements have dragbounds. closing.
