### ISSUE TITLE
Change color of pencil and eraser buttons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/charges-and-fields#40]
As reported in https://github.com/phetsims/scenery-phet/issues/92 by @pixelzoom:

> The problem is primarily the pink eraser. The common-code EraserButton lets you change the button color, but the eraser icon is an image file.

The pink eraser is not necessary for this sim. To make the common-code eraser image more visible on the button, the button color should be changed to RGB (242, 242, 242).

Here is a screenshot of the equipotential tool with updated buttons:
![image](https://cloud.githubusercontent.com/assets/8419308/7821870/e38cb8ca-03ae-11e5-8346-d3b15582ddba.png)

Assigning to @bereaphysics.

**Comment by pixelzoom** [comment]
Switched to scenery-phet.EraserButton in https://github.com/phetsims/charges-and-fields/commit/21cb8b45de8defc1215a0349aca9abd1ce102f14, changed PencilButton color in above commit.  Here's a screenshot:

![screenshot_530](https://cloud.githubusercontent.com/assets/3046552/7822387/595ea5ba-03b2-11e5-861f-85facd67d2e1.png)

**Comment by pixelzoom** [comment]
Assigning to @arouinfar for approval.  Note that the color looks darker than your screenshot, but I am indeed using rgb(242,242,242).

**Comment by arouinfar** [comment]
Thanks, @pixelzoom. Can you try #F2F2F2 instead?

**Comment by pixelzoom** [comment]
@arouinfar here is #F2F2F2:

![screenshot_531](https://cloud.githubusercontent.com/assets/3046552/7823358/2a1b91e0-03b8-11e5-81cc-4d15152905ff.png)

**Comment by pixelzoom** [comment]
@arouinfar here's '#F2F2F2'.

![screenshot_532](https://cloud.githubusercontent.com/assets/3046552/7823674/6f348b5e-03ba-11e5-9a30-1d9cc54efa9c.png)

**Comment by arouinfar** [comment]
Looks good, @pixelzoom! Closing.
