### ISSUE TITLE
Unable to open on Safari 6 w/ OS X 10.8

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/charges-and-fields#42]
Test device: MacBook Pro

Operating System: OS X 10.8

Browser: Safari 6.0 (8536.25)

Description: Sim doesn't start, displays black screen.

Steps to reproduce: Click on either test URLs in testing matrix.

Severity:

Screenshots: 
![screen shot 2015-06-22 at 12 55 29 pm](https://cloud.githubusercontent.com/assets/12610678/8290373/e72706de-18df-11e5-991b-e3b8862fe1f5.png)
![screen shot 2015-06-22 at 12 55 02 pm](https://cloud.githubusercontent.com/assets/12610678/8290375/ea521a92-18df-11e5-9f18-c9e6d2e14f70.png)

**Comment by veillette** [comment]
@elisemorgan : can you test the same platform but with the flag ?webgl=false in the url. I suspect it may have to do with it. Also for this case can you post  the 'report a problem' dialog.

**Comment by elisemorgan** [comment]
@bereaphysics I flagged ?webgl=false in both the testing URL and the iFrame URL and still nothing. In both, the PhET Interactive Simulations icon pops up for a second and displays "loading" then shows just the black screen above. Neither are giving me the option to 'report a problem.' Is there a way to access the dialog without the usual button?

**Comment by veillette** [comment]
Sorry for the oversight, of course you can't even access the 'report a problem' button. 

At this point we know that it is not due to the webgl mode. One would need to see the console in the developper tool to find out more about this issue. Since I dont have access to this platform i'll pass this issue to @ariel-phet to reassign to one of the developer.

**Comment by veillette** [comment]
Informed by @jonathanolson that "I think we don't support Safari 6 due to the heisenbug"
The test matrix was copy pasted from an old test matrix and might not reflect the platforms you have decided to drop recently.

**Comment by elisemorgan** [comment]
@ariel-phet should this issue be closed then?

**Comment by ariel-phet** [comment]
No, the issue should not be closed. Our sims should open on OSx 10.8.5 and Safari 6.2 -- for instance Molecule Shapes was tested on this platform.

Assigning to @jonathanolson to investigate

**Comment by jonathanolson** [comment]
@ariel-phet, the above test was for Safari 6.0 (unsupported), since our website mentions Safari 6.1+. I can check on a device here to see if 6.0 is the problem.

**Comment by jonathanolson** [comment]
Math.log10 isn't defined, should be easy enough to implement log base 10 with Math.log. Should I take care of the change?

**Comment by jonathanolson** [comment]
Implemented, let me know what I should do further.

**Comment by elisemorgan** [comment]
@bereaphysics Same issue in Win 8.1 w/ IE 11 with and without webgl=false

**Comment by arnabp** [comment]
Not on our testing matrix but on Windows 10, the issue exists in IE 11 but NOT on Edge (which works fine)

**Comment by veillette** [comment]
math.log10 is implemented on edge but not on IE11 or IE10. closing
