### ISSUE TITLE
Charge jumping distance while grabbed varies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#43]
The charges, when picked up from the bin, jump above the cursor higher than when they are picked up from the play field. I only say this because, on a touch screen, I am perfectly able to see the charge when grabbing from the bin, but when grabbing from the play area the charge doesn't jump up far enough and it is still hidden under my finger. In these gifs, the difference lies in the distance between the tips of the cursor hand and the bottom of the charge.

Grabbed from the bin (It's higher, I can see it on touch screens):

![chafi2](https://cloud.githubusercontent.com/assets/5863899/8291278/b5d2dfa8-18e5-11e5-881b-c1875755d7a2.gif)

Grabbed from the play area (It's lower, I cannot see it on touch screens):

![chafi3](https://cloud.githubusercontent.com/assets/5863899/8291318/02fa51b2-18e6-11e5-817d-d0eb74a8778f.gif)

Tested on Win 8.1
Troubleshooting information:
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/charges-and-fields_en.html
Version: 1.0.0-rc.1 2015-06-22 16:50:22 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.1 Mon Jun 22 2015 12:50:20 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"master"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"charges-and-fields":{"sha":"8fda05bfceb548a583cc0f84ac42afc36914bd44","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"master"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"master"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"master"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"master"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"master"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"master"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"master"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"master"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"master"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"master"}}

**Comment by veillette** [comment]
This is somewhat related to issue https://github.com/phetsims/charges-and-fields/issues/31.

This simulation has two distincts behaviors for the draghandlers. The first one applies only when you grab the charge/sensor from the enclosure (and is used until you release the charge) and there is a second drag handler behavior that applies to all subsequent drag events of the charge./sensor from the play area. 

To adress the issue at hand, it is relatively easy to increase the jumping distance, but it begs the bigger  question if we should not have a uniform behavior for the drag handlers (There were incompatible UI requirements on the two drag handlers hence the need for two), but maybe we should revisit.

**Comment by veillette** [comment]
To reiterate, the first drag handler put (initially) the charge/sensor at the edge of the enclosure (no matter the point of contact with the charge/sensor). Hence any dragging events will have an offset with the charge that depends on the point of contact. 

 The second draghandler, responsible for the dragging events on the play area, put the bottom of the charge at the tip of the cursor, 

So one drag handler adds an absolute offset whereas the other is an absolute offset. Unless there is a change in the specs, it is not possible to reconcile these two behaviors. 

Unless I get some input/directives from @ariel-phet or @arouinfar , i'll close this issue and leave as is.

**Comment by arouinfar** [comment]
It is very important that the charge peeks over the border of the panel when it first clicked. Without this behavior, students have trouble realizing that the charges are draggable. If there can only be one drag handler behavior, then I would prefer it to behave like the first drag handler @bereaphysics described in the previous post. However, I would prefer to leave the two drag handlers as is.

**Comment by veillette** [comment]
We will leave as is. Closing
