### ISSUE TITLE
Pencil icon a bit aliased on FF

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/charges-and-fields#45]
![pencil](https://cloud.githubusercontent.com/assets/4051174/8308906/b507e6f0-1984-11e5-812a-76b91e1fe92c.PNG)
The pencil icon on the equipotential tool seems a bit aliased on FF, perhaps consider mipmaping?

**Comment by veillette** [comment]
We have recently change to way we draw the pencil (see https://github.com/phetsims/charges-and-fields/issues/38) It was previously done in scenery code but we have switched to png. I'll look into mipmapping but we can always revert to the scenery code push come to shove.

**Comment by veillette** [comment]
The pencil image is mipmapped. Assigning to @ariel-phet to review once we issue a new release candidate.

**Comment by veillette** [comment]
@ariel-phet, @bryo5363, @phet-steele @elisemorgan: This should have been addressed in release candidate number 2. Keep an eye on this issue for the release candidate 2 and see if it has been fixed on firefox

**Comment by ariel-phet** [comment]
Appears fixed on my version of FF

**Comment by bryo5363** [comment]
On my version of FF (39.0) I still noticed some aliasing on rc-3

**Comment by ariel-phet** [comment]
I think what we see is acceptable and not worth pursuing a solution beyond mipmapping. Closing
