### ISSUE TITLE
Charge only stays at your finger during screen rotation after it's been placed in the play area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#48]
Another issue dealing with differences when grabbing from the bin versus grabbing from the play area. On tablets, grabbing from the bin then rotating the screen will not cause the charge to jump to the location of your finger. Grabbing from the play area and rotating the screen does however bring the charge to your finger.
Tested on an iPad Air 2.

**Comment by phet-steele** [comment]
Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/charges-and-fields_en.html
Version: 1.0.0-rc.1 2015-06-22 16:50:22 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 768x928
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.1 Mon Jun 22 2015 12:50:20 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"master"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"charges-and-fields":{"sha":"8fda05bfceb548a583cc0f84ac42afc36914bd44","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"master"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"master"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"master"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"master"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"master"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"master"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"master"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"master"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"master"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"master"}}

**Comment by jonathanolson** [comment]
I believe this has been fixed (we now use the "correct" drag no matter where the particle was originally dragged from), but I don't have an iPad handy at the moment.

**Comment by phet-steele** [comment]
@jonathanolson current master ends any dragging when the screen rotates, regardless of origin. Charges, sensors, etc.. are dropped wherever your finger was before rotating.

**Comment by samreid** [comment]
@andrewadare and I tested stock Apple apps and observed the default behavior was to end drags on screen rotate, so this behavior in the simulation seems acceptable.  Closing.
