### ISSUE TITLE
Sim does not open on Win 7 w/ IE 10

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/charges-and-fields#50]
After the PhET loading screen the sim page is completely black. This occurs with & without ?webgl=false

IE version: 10.0.9200.17357
Windows 7 Home Premium 64-bit

**Comment by veillette** [comment]
This is most likely due to the use of log10. Log10 is part of es6, not es5. This will be corrected in the next release candidate.

**Comment by veillette** [comment]
See #42

**Comment by veillette** [comment]
Closing

**Comment by elisemorgan** [comment]
@bereaphysics the sim opens on Win 7 w/ IE 10 now but becomes noticeably slower and choppier once the voltage is selected to appear.

**Comment by veillette** [comment]
@elisemorgan can you tell me if webgl was enabled. The info on the webgl status is contained in the report a problem log

**Comment by elisemorgan** [comment]
@bereaphysics webgl is not enabled

**Comment by veillette** [comment]
Thanks, unfortunately there isn't much we can do about the equipotential field. Some computers do not allow webgl, and the canvas fallback will be slower.  Fortunately there are less and less computers that are blacklisted
