### ISSUE TITLE
replace toFixed with dot.Util.toFixed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/charges-and-fields#52]
This sim uses JavaScript's built-in toFixed. This function should not be used directly; it is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Use dot.Util.toFixed, see its doc for details.

**Comment by veillette** [comment]
The fix was pushed to the 1.0 branch. It will be merged back to master later on.
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good. @bereaphysics I'm going to leave this open as a reminder to merge into master. When that's done, feel free to close this.

**Comment by veillette** [comment]
The RC branch was merged into master. Closing.
