### ISSUE TITLE
Why do charges not change the electric field when initially dragged from grabber?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/charges-and-fields#53]
I noticed that this is one of the only simulations where the initial "pull" of an object does not manipulate the "field". For example with the best fit, as the user clicked and dragged a new point the graph would instantly change to fit that point. Would we want to implement that here for this simulation? I think it would add a little bit to the experience rather than dropping the charge down first.

**Comment by veillette** [comment]
This behavior replicates the flash simulation and was specifically requested.

**Comment by veillette** [comment]
Admittedly it makes the UI a bit inconsistent. 
In any case, closing
