### ISSUE TITLE
The cursor should be a hand when mousing over the potentiometer in the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#57]
When mousing over the toolbox measuring tape, the cursor becomes a hand.  However for the potentiometer, it remains an arrow.  But making it become a hand will be another cue for users that it is draggable.

**Comment by veillette** [comment]
Good catch. The fix has been pushed to branch 1.0. it will be merged into master later on.

**Comment by veillette** [comment]
The fix was merged onto master. Closing
