### ISSUE TITLE
Clicking on a charge will cause it to move

### ISSUE THREAD

**Issue by bryo5363** [phetsims/charges-and-fields#58]
Test device: Windows desktop

Operating System: Windows 7 Enterprise

Browser: Chrome 43.0.2357.132 m

Problem description: Clicking a charge will cause it to shift position

Steps to reproduce:
1) open the simulation
2) bring up a charge into the field
3) click the charge. it will move

Severity:

Screenshots:

My cursor isn't shown but here I am simply clicking on the negative charge in the "charge reservoir"

![charges-and-fields](https://cloud.githubusercontent.com/assets/7717368/8555360/e13a653a-24ac-11e5-9345-a98522c9a518.png)

Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.3/charges-and-fields_en.html
Version: 1.0.0-rc.3 2015-07-04 01:00:50 UTC
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
Language: en-US
Window: 1447x928
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.3 Fri Jul 03 2015 21:00:43 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"HEAD"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"HEAD"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"HEAD"},"charges-and-fields":{"sha":"1f1baa1987432669a99bff108ee8458035c7d412","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"HEAD"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"HEAD"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"HEAD"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"HEAD"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"HEAD"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"HEAD"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"HEAD"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"HEAD"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"HEAD"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"HEAD"}}

**Comment by veillette** [comment]
Thanks @bryo5363, This touch behavior is a design decision. 
So closing.
