### ISSUE TITLE
Performance slowed on Win 8 w/ Chrome

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/charges-and-fields#59]
Test device: ASUS 

Operating System: Win 8.1

Browser: Chrome 44.0.2403.52 beta-m (64-bit)

Problem description: The performance of the sim is much slower with rc 3. There is a significant lag w/ choppiness to movement. Lag appears with and without voltage selected.

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.3/charges-and-fields_en.html
Version: 1.0.0-rc.3 2015-07-04 01:00:50 UTC
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.52 Safari/537.36
Language: en-US
Window: 1328x639
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.3 Fri Jul 03 2015 21:00:43 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"HEAD"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"HEAD"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"HEAD"},"charges-and-fields":{"sha":"1f1baa1987432669a99bff108ee8458035c7d412","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"HEAD"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"HEAD"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"HEAD"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"HEAD"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"HEAD"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"HEAD"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"HEAD"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"HEAD"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"HEAD"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"HEAD"}}

**Comment by elisemorgan** [comment]
Better, but still slow and choppy performance seen in IE 11 w/ Win 8. webgl is enabled.

**Comment by veillette** [comment]
I think it is worth investigating this further. These only significant difference between release candidate two and three is the switch of the rendering engine for the electric field (the grid of arrows). In regular candidate 2 this was done with svg, whereas rc 3 uses canvas node. On some platforms, notably the iPad, rc3 is more responsive. The claim here is that for win8 on chrome, it is better with the svg renderer. 

We could possibly try to find a heuristic criterion that could decide on the fly which rendering to use for the electric Field node.  

Before we move forward with this ,though, i would like to confirm that I  have a correct understanding of the issue .

Can you confirm @elisemorgan ?

**Comment by elisemorgan** [comment]
@bereaphysics  That's correct

**Comment by veillette** [comment]
@jonathanolson 
 There are two nodes electricFieldGridNode and electricFieldCanvasNode. We would like to develop a heuristic criterion that would allow us to pick whichever is faster. At this pinning it is not clear what kind of criterion is relevant. At this point we know that the iPad works faster on canvasNode but win8 with chrome is faster with svg. 

Two questions:
Have you come across this before?

Do you think this is purely a browser thing, or does the OS plays  a role, or the speed of the computer, etc matter?

FYI, all the new commits have been done on branch 1.0

**Comment by jonathanolson** [comment]
I'd prefer to be able to review the code and performance for each, so that we could potentially just have one well-performing option.

For instance in ElectricFieldGridCanvasNode, there are things that look like they can be moved out of inner loops, like the following line:

``` js
var bounds = self.modelViewTransform.modelToViewBounds( self.availableModelBoundsProperty.get().dilated( ELECTRIC_FIELD_SENSOR_SPACING / 2 ) );
```

along with a number of other potential ways to speed up the code (creating a Canvas with an arrow drawn into it, and using that as an image to draw could potentially be way faster).

How can I switch between the two options (to profile), and where is the code for each option?

**Comment by veillette** [comment]
There is a static flag in ChargesAndFieldsScreenView IS_CANVAS_ELECTRIC_FIELD_GRID that is used to determine if canvasNode is utilized

**Comment by veillette** [comment]
Feel free to optimize canvasNode. In fact this piece of code has not been reviewed since it was done after the code review

**Comment by jonathanolson** [comment]
This was reported before WebGL was used. We'll re-open if it's a problem in future RCs.
