### ISSUE TITLE
Changes to make to the latest dev version (1.0.0-dev.4)

### ISSUE THREAD

**Issue by arouinfar** [phetsims/charges-and-fields#6]
As discussed with @bereaphysics and @ariel-phet , there are a few changes to make to the latest dev version.
- [x] E-field should be turned on by default.
- [x] Move equipotential tool, tape measure, and grid to separate toolbox (AR will mock this up and send to MV)
- [x] It should not be possible to drag the equipotential tool, charges, or sensors off screen.
- [x] Increase the area that the E-Field and Voltage are drawn in to support monitors with a wider aspect ratio or a vertical iPad.
- [x] If the window is resized such that the equipotential tool is off screen, it should pop back onto the screen.<br>
  ~~If the window is resized such that a charge and/or sensor is no longer visible, it should be removed from the playspace and the E-field and Voltage should be recalculated.~~
- [x] If a charge or sensor is clicked/touched within the click/touch boundaries, the charge should move so that it is directly above the cursor location. Example:

![image](https://cloud.githubusercontent.com/assets/8419308/6493205/64700ab6-c276-11e4-8130-e4b53d5d41d3.png)
- [x] When the window is vertically enlarged, the panels and reset all button should remain fixed in their position relative to the nav bar (similar to Energy Skate Park: Basics).
  ![image](https://cloud.githubusercontent.com/assets/8419308/6475304/bd53f5f4-c1c5-11e4-838c-2c8568ae61d7.png)
- [x] When there are no charges in the play space, the Electric Field arrows should never be visible. 

![image](https://cloud.githubusercontent.com/assets/8419308/6475194/cc693b54-c1c4-11e4-8125-280d804c8d40.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/6475161/90fbcc12-c1c4-11e4-8dda-e37492f50994.png)
          E-Field on (left) and Direction Only (right) with an empty play space.
- [x] The E-Field and Voltage should not draw (or update) until a charge is dropped into the playspace.

Assigning to @ariel-phet to see if there is anything else that should be added to this list.

**Comment by veillette** [comment]
One change to the request
-if the bounds are changing the charges are moving (instead of disappearing) to stay within the 'play' area.  
In addition
- work remains to be done on the common code component (measuring tape) since it cannot handle dynamical bounds at the moment.
- the toolbox remains to be done.
- voltage and electric field grid response time is very subpar on ipad2.

**Comment by veillette** [comment]
Assigning to @arouinfar to create separate issues for tickets that have not been addressed.

**Comment by arouinfar** [comment]
Final outstanding issue has been moved to #8. Closing.
