### ISSUE TITLE
mipmap.js registers image incorrectly when used with optional arguments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/charges-and-fields#60]
This sim appears to contain an unused image. `grunt build` reports:

```
Running "after-requirejs-build" task
>> Unused image: CHARGES_AND_FIELDS/pencil.png
```

**Comment by pixelzoom** [comment]
Hmmm... This image is indeed used, in PencilButton.js:

>   var pencilImage = require( 'mipmap!CHARGES_AND_FIELDS/pencil.png,level=5' );

And PencilButton.js is used in the sim.

This may a bug in reportUnsedMedia.js.  @samreid Does reportUnsedMedia.js take into account the optional args that may appear after the filename?

**Comment by pixelzoom** [comment]
At line 41 of reportUnusedMedia.js, I added:

`console.log( 'filename=' + filename );`

.. and the output during `grunt` was:

```
Running "after-requirejs-build" task
filename=electricPotentialPanelOutline.png
filename=license.json
filename=pencil.png
```

Ah... But this is what's in the filesystem.

**Comment by pixelzoom** [comment]
I inspected `global.phet.chipper.licenseEntries.images`, and the key for pencil.png is incorrect, it contains the mipmap options.  Here's the entry:

``` js
'CHARGES_AND_FIELDS/pencil.png,level=5': 
   { text: [ 'Copyright 2002-2015 University of Colorado Boulder' ],
     projectURL: 'http://phet.colorado.edu',
     license: 'contact phethelp@colorado.edu',
     notes: 'created by Amy Rouinfar' },
```

**Comment by pixelzoom** [comment]
The bug is in mipmap.js.  The `name` arg, which is everything after 'mipmap!' in the plugin invocation, is passed to `registerLicenseEntry` on line 110:

`registerLicenseEntry( name, getLicenseEntry( path ), global.phet.chipper.brand, 'images', onload );`

**Comment by pixelzoom** [comment]
So... This is a general issue that will occur with any usage of mipmap that involves its optional arguments. mipmap.js needs to be fixed to strip off the arguments before passing the name to registerLicenseEntry.

**Comment by pixelzoom** [comment]
Note that mipmap currently has 2 optional arguments. From mipmap.js:

``` js
 * There are currently two main options to be provided:
 * level - What the maximum mipmap level computed should be. Level 0 is the original image, level 1 is a half-size
 *         image, level 2 is a quarter-size image, etc. Default value is up to level 4. If -1 is passed as the level
 *         then all mipmap levels up to a 1x1 image will be computed. Mipmaps will only be computed up to a 1x1 image
 *         if a higher maximum level was set.
 * quality - Currently the JPEG encoding quality (1-100) for when JPEG images are an output option (which happens when
 *           the entire image is fully opaque). Default is 98. This parameter is only used for the build, as the
 *           require.js runtime version will always use PNG (the browser default for toDataURL()).
```

So the solution to this should be robust enough to work a variable number of args.

**Comment by pixelzoom** [comment]
Fixed.  Tested with charges-and-fields (which uses mipmap with optional args) and with molecules-and-light (which uses mipmap with no args). 

Inspecting `global.phet.chipper.licenseEntries.images` for charges-and-fields now shows a proper key for the license entry:

```
'CHARGES_AND_FIELDS/pencil.png': 
   { text: [ 'Copyright 2002-2015 University of Colorado Boulder' ],
     projectURL: 'http://phet.colorado.edu',
     license: 'contact phethelp@colorado.edu',
     notes: 'created by Amy Rouinfar' },
```

Assigned to @samreid to verify.

**Comment by samreid** [comment]
Thanks for detecting and fixing this. The change set looks good.  My only question is whether we should filter out the optional arguments in registerLicenseEntry.js (in case other plugins acquire options in the future).

**Comment by pixelzoom** [comment]
> whether we should filter out the optional arguments in registerLicenseEntry.js

That would assume that all plugins adopt the grammar described in the documentation for mipmap.js. That's probably a reasonable assumption, but then the documentation should probably moved, the code for parsing options should be generalized, etc.  I don't feel compelled to tackle that right now, since I think the likelihood of adding options to new|existing plugins in the near future is small. Back to @samreid in case you'd like to take it on. Otherwise, feel free to close this issue, and perhaps create a (low priority) issue about generalizing the grammar and code related to options.

**Comment by samreid** [comment]
Let's close this issue and open a new in the future if/when other plugin arguments come in to play.
