### ISSUE TITLE
Field lines with no charges present

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#64]
Fuzz testing has revealed it's possible to cause the sim to display electric field lines when there are no charges present; still looking for a way to reproduce manually. Happens in all browsers on Win 8.1.

![present arrows](https://cloud.githubusercontent.com/assets/5863899/9446858/3dc72a4e-4a51-11e5-9f2e-5bf6f6678bb0.PNG)

Troubleshooting information:
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.4/charges-and-fields_en.html
Version: 1.0.0-rc.4 2015-08-21 15:43:30 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"5be7fe04","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"ffae69f4","branch":"master"},"charges-and-fields":{"sha":"c610f581","branch":"1.0"},"chipper":{"sha":"9b362c00","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a6ea86cb","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"e33e2f8c","branch":"master"},"scenery":{"sha":"3c146e8f","branch":"master"},"scenery-phet":{"sha":"1fa88998","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"e400abb4","branch":"master"}}

**Comment by phet-steele** [comment]
Got it! Pretty simple actually:
1. Put some charges out
2. Click/touch reset all
3. Enable "Direction Only"

**Comment by phet-steele** [comment]
I can also confirm this happening in iOS 8.3, iPad Air 2.

**Comment by phet-steele** [comment]
This also affects the sensor, it will display "0.0 deg" when the Values box is checked.

**Comment by jessegreenberg** [comment]
This is resolved in the commit above.  Field lines and sensors behave as expected when there are no active charges. Closing.

**Comment by phet-steele** [comment]
@andrewadare do this:
1. Ensure E-filed is turned on
2. Put at least two charges into the field
3. Reset all
4. Enable Direction Only

The following image is close to what you will get.

<img width="1919" alt="screen shot 2016-08-02 at 1 12 27 pm" src="https://cloud.githubusercontent.com/assets/5863899/17341708/1323c092-58b3-11e6-972d-6cca301fc6a6.png">

The bigger issue here is that no field lines should be present with no charge (as discussed in #46), but even just from start-up, you can click on Direction Only and see field lines. Seeing this happen on every device/browser. For phetsims/tasks/issues/661.

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.17, closing.
