### ISSUE TITLE
Prepare for research study

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#67]
Similar to https://github.com/phetsims/beers-law-lab/issues/139

Ido and Sarah requested:

> We (UBC) are meeting again tomorrow to design our study this term. Can you estimate whether preparing the two sims (Beer’s Law; Charges and Fields) will be ready for March? “ready” means
> - backend data instrumentation
> - custom start state
> - label changes, availability of features, other minor screen adaptations.
>   Perhaps also
> - ability of students to report out screen state (and capture somehow, somewhere).

At Thursday's phet-io meeting @ariel-phet recommended that @jonathanolson work with @samreid to instrument the simulation, so I'll assign it to @jonathanolson, but we'll need to coordinate to get it ready.

**Comment by samreid** [comment]
Ido continued:

> After our meeting today, we have identified the following minor changes to the sims that would really facilitate our study:
> - remove e-field sensors
> - remove “show e-field” switch; keep default off.
> - remove show-numbers; keep default off.
> - enable the measuring tape (without the show-numbers).
> - remove scale from grid (so that it's unitless)
> 
> Ideally we would have these changes as early as beginning of February so that we can have a pilot study with a handful of students. Is this doable?

Rather than publishing a custom version, I'd like to deliver a phet-io version that customizes the simulation as described

**Comment by samreid** [comment]
@kathy-phet asked about removing the e-field sensors:

> motivation? are you not wanting to investigate e-fields relationship? 

Ido replied:

> The task will involve the potential, and fields may confuse.

**Comment by samreid** [comment]
@kathy-phet asked about enabling the measuring tape without shown numbers:

> how would you use the tape if it did not have numbers? 

Ido replied:

> The tape will always have numbers - we just don’t want the “show numbers” switch.

**Comment by samreid** [comment]
Jan 14 Meeting: @ariel-phet recommended for @jonathanolson to work on this at high priority, meeting with @samreid to get started.

**Comment by jonathanolson** [comment]
Instrumentation is now enough where I can start testing with Ido's setup (charges-and-fields_en.html?ea&brand=phet-io&phet-io-standalone&togetherEvents.log=lines&together.expressions=%5B%5B"chargesAndFields.chargesAndFieldsScreen.model.isElectricFieldVisibleProperty"%2C"setValue"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.chargesAndSensorsPanel.electricFieldSensor"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%5D).

![charges-and-fields-ido-1](https://cloud.githubusercontent.com/assets/480878/12528598/ae9f6d02-c158-11e5-9c4d-95602b15fe2f.PNG)

We'll need to set up layout and remove the "Sensors"  text in the bottom panel, and I'll need to iron out and complete some instrumentation choices (and lots of sim bugs).

**Comment by kathy-phet** [comment]
Hi JO, met with Ido today. He is going to do some pilot interviews before finalizing sim config. They are still figuring that out it seems and will just use the full sim for their interview treating of their activity. So just focus on general instrumentation and sim bugs, not ido's specific request. When instrumentation is far enough along, we will get ido to review that part - maybe delivery that in another week when we have stuff on PhETiO website?

This sim will also likely be of pretty high interest to some of our PhETiO prospects.

Best,
Kathy

Sent from my iPhone

On Jan 22, 2016, at 10:38 PM, Jonathan Olson <notifications@github.com<mailto:notifications@github.com>> wrote:

Instrumentation is now enough where I can start testing with Ido's setup (charges-and-fields_en.html?ea&brand=phet-io&phet-io-standalone&togetherEvents.log=lines&together.expressions=%5B%5B"chargesAndFields.chargesAndFieldsScreen.model.isElectricFieldVisibleProperty"%2C"setValue"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.chargesAndSensorsPanel.electricFieldSensor"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%2C%5B"chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckBox"%2C"setVisible"%2C%5Bfalse%5D%5D%5D).

[charges-and-fields-ido-1]https://cloud.githubusercontent.com/assets/480878/12528598/ae9f6d02-c158-11e5-9c4d-95602b15fe2f.PNG

We'll need to set up layout and remove the "Sensors" text in the bottom panel, and I'll need to iron out and complete some instrumentation choices (and lots of sim bugs).

##

**Comment by samreid** [comment]
@jonathanolson what is the status of this issue?  Do you have any outstanding work? Is this mostly ready for review?

**Comment by jonathanolson** [comment]
I'll still need to instrument a few more parts, and I haven't reviewed/tested/worked on state saving for particles. Additionally, bugfixes and sim improvements will still be needed.

**Comment by jonathanolson** [comment]
Noting here that equipotential lines were not handled before, will need implementation. I'll also be reviewing @samreid's state saving, and going through testing.

**Comment by kathy-phet** [comment]
@jonathanolson - Just want to clarify that we are not doing any specific customizations for Ido anymore as he will not use it in a study, but are still aiming to have the sim fully instrumented since it will be a good exemplar for PhET-iO.

**Comment by jonathanolson** [comment]
Understood, will do.

**Comment by ariel-phet** [comment]
Since @andrewadare is actively instrumenting this sim, this issue seems stale. Closing
