### ISSUE TITLE
Some i18n tweaks

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/charges-and-fields#70]
As discussed on skype call with @jonathanolson we should make a few tweaks for i18n
1. The charge/sensor panel layout should be redone to accommodate long strings and keep the spacing, centering, and layout nice
2. Tweak equipotential sensor so that body size does not change with long strings.

**Comment by jonathanolson** [comment]
Should be handled, can you see if it's sufficient?

**Comment by ariel-phet** [comment]
@jonathanolson in the latest pull the charge and sensor panel scales appropriately with ?stringTest=double but the equipotential meter is still growing unnecessarily for me.

**Comment by jonathanolson** [comment]
Whoops, somehow I had reverted a change I had made locally. Committed, try again?

**Comment by ariel-phet** [comment]
Yes, much better. Closing
