### ISSUE TITLE
Pressing buttons on electric potential sensor starts a drag

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/charges-and-fields#73]
Presumably you shouldn't be able to drag it by its buttons.

**Comment by jonathanolson** [comment]
Looks like something tricky:
1. listener() for the push buttons isn't passed the Scenery event, so we can't call event.handle() to fix this (simplest/best)
2. No great future-proof way of overriding this in SimpleDragHandler.

Thus the current workaround is:

``` js
    this.movableDragHandler.tryToSnag = function( event ) {
      if ( !_.contains( event.trail.nodes, clearButton ) && !_.contains( event.trail.nodes, plotElectricPotentialLineButton ) ) {
        MovableDragHandler.prototype.tryToSnag.call( this, event );
      }
    };
```

Tagging for developer meeting to discuss if we can get the Scenery event nicely through the button interface, OR if buttons should handle() on their own by default.

**Comment by samreid** [comment]
There is a similar case in Concentration, where you can drag the dropper by its button.

**Comment by pixelzoom** [comment]
I believe that @samreid is referring to the eye dropper that appears in Beer's Law Lab and Concentration (beers-law-lab.BLLDropperNode).  In that case, the button is a momentary button, and it was desired to be able to move the dropper while dispensing.

**Comment by pixelzoom** [comment]
I believe that @samreid is referring to the eye dropper that appears in Beer's Law Lab and Concentration (beers-law-lab.BLLDropperNode).  In that case, the button is a momentary button, and it was desired to be able to move the dropper while dispensing.  So we shouldn't do anything that would _prevent_ this behavior.

**Comment by pixelzoom** [comment]
2/2/16 dev meeting; Deferred to 2/4/16 when @jonathanolson is available.

**Comment by samreid** [comment]
@jonathanolson says we will need access to other information in the event, such as which pointer is active, etc. and would like investigate a global that keeps track of the current event.

**Comment by pixelzoom** [comment]
Rather than a global or addition button options, @jonathanolson is going to investigate simply adding an additional input listener. Eg:

``` js
var myButton = new RoundPushButton(...);
myButton.addInputListener( {
  // a listener that marks events as handled
} );
```
