### ISSUE TITLE
Drop bounds for the measuring tape

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/charges-and-fields#74]
Dragging the measuring tape here doesn't drop it back into the toolbox, because both ends are outside of it:

![charges-and-fields-drop-measuring-tape](https://cloud.githubusercontent.com/assets/480878/12525816/b02b8130-c124-11e5-85cc-28d66e23e3a8.PNG)

Is that expected behavior, or should a reasonable level of overlap cause it to go back into the toolbox?

**Comment by arouinfar** [comment]
No, that is not the expected behavior. If there's a reasonable amount of overlap, the measuring tape should go back into the toolbox.

**Comment by jonathanolson** [comment]
Done.
