### ISSUE TITLE
Error on dragging charge and electric field sensor to same location

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/charges-and-fields#75]
Presumably tries to do something with infinity. Scenery notices the NaNs and fails out.

@arouinfar, what would you like the readout to be for a sensor when "Values" are checked and it is directly over a charge?

**Comment by arouinfar** [comment]
@jonathanolson I think it'd be best to display a dash when the sensor detects infinity/NaN. We've used the dash in other simulations like Concentration (probe reads a dash when it not in the solution) to indicate a readout is unavailable. I realize an infinite readout is not the same as no readout, but it seems the more appropriate to display a dash than something infinity or NaN.

**Comment by jonathanolson** [comment]
Dashes are a bit harder to see. I set it to center the labels over the sensor (instead of left-aligned 20px to the left), so that the dashes will be over the charge at least.

Try it out, let me know if it should be changed?

**Comment by ariel-phet** [comment]
@arouinfar pinging on this issue

**Comment by arouinfar** [comment]
@jonathanolson I think the dash looks pretty good, and I think centering the labels was a good call. I agree that it's a bit hard to see, but I don't particularly like any of the alternatives (infinity, NaN). Given that it's a bit of an edge case to begin with, I can live with it being a little less visible.
