### ISSUE TITLE
Why ignore non-left mouse button?

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#76]
Based on discussion in https://github.com/phetsims/scenery-phet/issues/195#issuecomment-186300071 I was looking at Charges and Fields as a prototype for how to build toolbox+creation for circuit construction kit and I saw this code:

``` js
        // Ignore non-left-mouse-button
        if ( event.pointer.isMouse && event.domEvent.button !== 0 ) {
          return;
        }
```

Why are you ignoring non-left-mouse-button?  Can/should this be factored out somewhere?

**Comment by jonathanolson** [comment]
If this pattern becomes common, we could shift the check into SimpleDragHandler's startDrag.

We only want to track the up/down of the left mouse button, since the "press LMB down, press and release RMB" would stop the drag, and other mouse buttons would normally be for other things.

@samreid, sound good to investigate moving this check to SimpleDragHandler?

**Comment by samreid** [comment]
I'll flag this for discussion at developer meeting.

**Comment by samreid** [comment]
There are 3 occurrences of this pattern in Charges and Fields, and one in Circuit Construction Kit.

**Comment by samreid** [comment]
Meeting consensus.  We agreed it would be nice to factor this out.  @jonathanolson will take a look.

**Comment by jonathanolson** [comment]
This gets trickier if you think about subtyping SimpleDragHandler.

If we put the guard in at the front of startDrag(), then there's no way to communicate to subtypes whether the drag will actually start UNTIL they call the super startDrag(). We would potentially need to return a success value from startDrag.

**Comment by veillette** [comment]
This issue is stale since there is no such code in charges and fields. Event has a method called canStartPress that carries out this function.

```
    canStartPress: function() {
      // If the pointer is already attached (some other press probably), it can't start a press.
      // Additionally, we generally want to ignore non-left mouse buttons.
      return !this.pointer.isAttached() && ( !this.pointer.isMouse || this.domEvent.button === 0 );
    }
```
