### ISSUE TITLE
When running as phet-io, the PhET Menu "Options" button causes a failure

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#79]
When running as phet-io, the PhET Menu "Options" button causes a failure,

![image](https://cloud.githubusercontent.com/assets/679486/16503293/a959697a-3ecf-11e6-8dcf-636828b1a2e2.png)

**Comment by andrewadare** [comment]
Problem now seems to be a little different than originally reported. There's no problem when selecting "Options..." the first time, but the second click triggers this error:

```
Assertion failed: phetioID already registered: chargesAndFields.navigationBar.phetButton.phetMenu.optionsDialog.closeButton
```

If the merge of phet-io-types (see https://github.com/phetsims/phet-io/issues/498) is imminent, seems best to wait for that first.

**Comment by samreid** [comment]
It seems we need to do one of the following:
- Dispose and make sure tandem.removeInstance() is called

or
- Only instantiate/register the close button once

**Comment by andrewadare** [comment]
Blocked by https://github.com/phetsims/phet-io/issues/497. I just marked that issue as high priority.

**Comment by andrewadare** [comment]
https://github.com/phetsims/phet-io/issues/720 Has progressed to the point that this issue is no longer blocked.

Pushing the options button, then closing it, then pushing it again triggers this error:

Assertion failed: Cannot register two different instances to the same id

**Comment by andrewadare** [comment]
PhetMenu appears to have full Tandem support and implements dispose(), but OptionsDialog and CloseButton do not.

**Comment by andrewadare** [comment]
The optionsDialog instance in PhetMenu was made persistent, and although dispose() was not fully implemented in OptionsDialog, this bug is now fixed.
