### ISSUE TITLE
Toolbox for equipotential tool and tape measure

### ISSUE THREAD

**Issue by arouinfar** [phetsims/charges-and-fields#8]
As mentioned in #6, we would like to put the equipotential tool and tape measure in a toolbox. 

Here's an updated mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/6718050/72d9a1ce-cd76-11e4-809c-e5f6e3e6607d.png)

When clicking on a tool, it should grow to its full size. The equipotential tool will move so that the grab pad at the bottom of the tool is at the cursor location. The tools must be dragged beyond the boundaries of the toolbox to be placed in the play space (like the charges/sensors). 
![image](https://cloud.githubusercontent.com/assets/8419308/6718103/dae7b918-cd76-11e4-929d-7c9bdce0cae1.png) ![image](https://cloud.githubusercontent.com/assets/8419308/6718106/e5dd8474-cd76-11e4-8fd5-fbdd547ff093.png)

The updated mockup and assets have been sent to @bereaphysics.

**Comment by veillette** [comment]
The toolbox has been completed. closing
