### ISSUE TITLE
use activeChargedParticles for all electric Field and electric potential calculations

### ISSUE THREAD

**Issue by veillette** [phetsims/charges-and-fields#80]
There are currently two observable arrays that keep track of the charged particles, namely chargedParticles and activeChargedParticles.  

The activeChargedParticles contains all the charges that are active, that is that can have an effect of the electric field and electric potential. (In some cases, the charges are inactive, for instance when being dragged initially). The chargedParticle array keep track of all the charged particles, regardless of the active/inactive status. 

The calculations for the webGl node are carried out using the activeChargedParticles whereas the calculations for some of the non-webgl features relies on chargedParticles (while checking that the 
particles are active.) 

This is redundant  and possibly confusing for future maintenance. 

For instance, the getElectricField and getElectricPotential  methods could be rewritten to run over the activeChargedParticles array instead.

**Comment by andrewadare** [comment]
@veillette are you planning to to take this on? If so, what is the timeframe? The sim is in dev testing and heading towards the RC phase once the testing issues are resolved.

**Comment by veillette** [comment]
@andrewadare : I was not planning to work on it. I just noticed it while I was commenting on another issue.
 If you don't think it is worth it to work on it, feel free to close it.
