### ISSUE TITLE
Undefined sensors will not update their values

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#82]
Undefined sensors will not update their values until new charges are added to the field (or the sensors themselves are moved). This results in sensors with incorrect displays:
1. Put a sensor on top of a charge to nullify its values
2. Move the same charge
![caf02](https://cloud.githubusercontent.com/assets/5863899/17305746/44f9822a-57e9-11e6-8298-c3721bdb1251.gif)

Seen on OSX 10.11.6 Chrome & Safari. For phetsims/tasks/issues/661.
Troubleshooting information:
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.15/charges-and-fields_en.html
Version: 1.0.0-dev.15 2016-07-28 14:16:27 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"56e95e01","branch":"master"},"babel":{"sha":"b0a15003","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"charges-and-fields":{"sha":"9163b74d","branch":"master"},"chipper":{"sha":"bdc6b525","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"50af4ae6","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"eaa4be69","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"85b7fc95","branch":"master"},"tandem":{"sha":"6cc3e843","branch":"master"}}

**Comment by andrewadare** [comment]
I looked at ways to modify the update logic to handle this corner case, but haven't found a way that doesn't have other problems.

Instead, I made the corner-case (hopefully) inaccessible now. You can't drag the charge out from underneath the probe particle anymore, which seems completely fine to me, and is a safe solution.

**Comment by phet-steele** [comment]
This solution would not solve the case of dragging a particle over the center of a sensor, then dragging the particle away:

![caf03](https://cloud.githubusercontent.com/assets/5863899/17343505/493de376-58bb-11e6-9424-8fb88a011021.gif)

**Comment by andrewadare** [comment]
That is true, will revisit.

**Comment by phet-steele** [comment]
Fixed in 1.0.0-dev.17, closing.

**Comment by phet-steele** [comment]
Actually not fixed, noticed while verifying another issue:

The sensors will not update if placed _exactly_ in the center. Furthermore, in the case of dragging a particle on top of a sensor, if the particle is _exactly_ over the center of the sensor, the sensor will have a reading that effectively ignores the particle above it (end of the video):

![caf06](https://cloud.githubusercontent.com/assets/5863899/17669512/2425b554-62cb-11e6-8025-87baee7a1588.gif)

**Comment by andrewadare** [comment]
The getElectricFieldChange function is what's causing the second problem (i.e. update failures with a charge dragged directly atop the sensor). I've spent several hours on this today, and I can reduce its probability of occurrence, but I have been unsuccessful making it completely go away.

That function was written as a second, more efficient implementation of the E-field calculation. It starts with the pre-existing field measurement and updates it with a delta E term. Sometimes it fails near r=0 and cannot seem to recover afterwards. I haven't been able to find a good fix for that condition yet.

So I'm reverting to the updateAllSensors() call in the positionListener for the charged particles. That seems to work correctly every time. We will have to live with this less-efficient implementation unless I (or someone else) can find a better fix for this.

**Comment by phet-steele** [comment]
Fixed, closing. Thank you @andrewadare.
