### ISSUE TITLE
div/0 error

### ISSUE THREAD

**Issue by andrewadare** [phetsims/charges-and-fields#84]
While trying to reproduce #82, I dragged a sensor atop a charge and received an error from Vector2 saying 'Cannot normalize a zero-magnitude vector'.

Will need to put in a check for length-zero vectors in the code that does the normalization.

**Comment by andrewadare** [comment]
This is occurring atop a deep stack of scenery code calls...
![image](https://cloud.githubusercontent.com/assets/154163/17311357/fef123a4-5807-11e6-8e05-d58765cd0c25.png)

A proper fix may therefore involve some work there.

Alternatively, perhaps a drag constraint could be applied so that the sensor snaps to some minimum radius from the charge.

**Comment by andrewadare** [comment]
Hmm...this error is turning out to be very difficult to reproduce. Several minutes of dragging, still no singularity.

**Comment by andrewadare** [comment]
Just hit this again:
![image](https://cloud.githubusercontent.com/assets/154163/17336192/46c905b0-589a-11e6-9915-b66250c36447.png)

**Comment by andrewadare** [comment]
We need a "Heisenbug" label :)

**Comment by andrewadare** [comment]
@phet-steele discovered that the bug is reproducible by turning on the grid for reference, dropping a charge at (x=anything, y=3 major ticks down), and putting the sensor atop the charge. The error is then triggered every time.

**Comment by andrewadare** [comment]
`getElectricField` in ChargesAndFieldsModel computes a distance (cubed), which then appears downstairs in the following Coulomb field calculation. Since javascript allows division by zero, the code continues even if r=0, but these are the times when the bug is triggered.

**Comment by andrewadare** [comment]
Things are better now, but there's an annoying single-pixel position at r=0 where the field is reported as zero rather than '-'. More work needed.

**Comment by phet-steele** [comment]
Can't make this happen anymore, let's hope we never see it again.
