### ISSUE TITLE
Reading on the meter goes off of the meter itself 

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/charges-and-fields#85]
For phetsims/tasks#661
Testing Device: Personal Laptop
Mac 10.11.6, Safari

Problem Description: When the equipotential meter is placed in the center of the charges, the reading on the meter goes off of the meter itself.

Steps to Reproduce:
1. Drag a positive and negative charge onto the screen
2. Place the equipotential meter in the center of the charge

![image](https://cloud.githubusercontent.com/assets/19288972/17335839/c6b6e960-5898-11e6-87c2-65291e16e8f7.png)

![image](https://cloud.githubusercontent.com/assets/19288972/17335863/d504a46c-5898-11e6-8bd7-bf8fcaf409aa.png)

Troubleshooting information (do not edit):
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.15/charges-and-fields_en.html
Version: 1.0.0-dev.15 2016-07-28 14:16:27 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7
Language: en-us
Window: 1423x751
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 ATI-1.42.15)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"56e95e01","branch":"master"},"babel":{"sha":"b0a15003","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"charges-and-fields":{"sha":"9163b74d","branch":"master"},"chipper":{"sha":"bdc6b525","branch":"master"},"dot":{"sha":"6ee3c51e","branch":"master"},"joist":{"sha":"50af4ae6","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"eaa4be69","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"85b7fc95","branch":"master"},"tandem":{"sha":"6cc3e843","branch":"master"}}

**Comment by phet-steele** [comment]
Looks good in 1.0.0-dev.17.
