### ISSUE TITLE
Arrow on the sensor shows up when all the charges are placed back in the particle box

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/charges-and-fields#88]
For phetsims/tasks/issues/678
OSX 10.11.6
Chrome

Problem Description: An arrow on the sensor still shows up when all charges are placed back in the particle box

Steps to Replicate:
1. Place a charge and a sensor in the play area
2. Place the charge back into the item box, notice that the arrow still appears on the sensor

Screenshots:
![image](https://cloud.githubusercontent.com/assets/19288972/17748860/8c8cbba2-6478-11e6-932d-d4f54225deb0.png)

Troubleshooting information (do not edit):
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.18/charges-and-fields_en.html
Version: 1.0.0-dev.18 2016-08-17 16:40:49 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1379x715
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"b8e116ae","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"charges-and-fields":{"sha":"aa265bdd","branch":"master"},"chipper":{"sha":"04bae4ef","branch":"master"},"dot":{"sha":"af08db1f","branch":"master"},"joist":{"sha":"9416be0b","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0ab22ac3","branch":"master"},"scenery-phet":{"sha":"fe2956ba","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"60408c95","branch":"master"},"tandem":{"sha":"43ebdfb3","branch":"master"}}

**Comment by andrewadare** [comment]
@alynne-phet good catch, I can easily reproduce this. Will see what I can do....

**Comment by andrewadare** [comment]
Should be fixed on master, won't show up until 1.0.0-dev.19+

**Comment by phet-steele** [comment]
Fixed, thanks @andrewadare. Closing.
