### ISSUE TITLE
Should we move the panels outside of the dev boundary when at wider aspect ratios?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/charges-and-fields#9]
In ESPB, the panels move slightly outside of the dev boundary when at wider aspect ratios:
![image](https://cloud.githubusercontent.com/assets/8419308/6807978/3eacca66-d217-11e4-99c2-c2d2ddf1806a.png)

Should we do the same thing for Charges & Fields? We would open up the play space quite a bit if the panel + toolbox (not pictured) could be moved to the right. 
![image](https://cloud.githubusercontent.com/assets/8419308/6808310/f8a12696-d218-11e4-9107-fb467dbe8dca.png)

Assigning to @ariel-phet for input.

**Comment by ariel-phet** [comment]
Agreed, it would be a nice touch.

**Comment by veillette** [comment]
Ok i'll look into implementing this feature

**Comment by veillette** [comment]
Done closing
