### ISSUE TITLE
Public tandem instance marked TODO

### ISSUE THREAD

**Issue by andrewadare** [phetsims/charges-and-fields#90]
@samreid I'm in the process of cleaning up TODO's in Charges and Fields, and came across a public tandem instance marked with TODO in [the ChargesAndFieldsModel constructor](https://github.com/phetsims/charges-and-fields/blob/421fff7b0c5be179a66b675db63e48d66576d657/js/charges-and-fields/model/ChargesAndFieldsModel.js#L45-L46).

I know you did not instrument this sim, but do you see this as a problem? If so, do you have any recommendations on how to change it?

**Comment by samreid** [comment]
All of the `this.tandem = tandem` should be removed.  In the 3 cases where the `this.tandem` was being used for dispose, we should convert to the standard dispose pattern in which the tandem remains a closure (local) variable.

**Comment by andrewadare** [comment]
@samreid thanks for the guidance. Is `this.tandem = tandem` a general anti-pattern? If so, there are appearances in Beer's Law Lab that may require attention.

**Comment by andrewadare** [comment]
I also see a usage in ESPB with an explicit at-private annotation, which is presumably okay.

**Comment by samreid** [comment]
It was a strategy we investigated something like 8 months ago, and I would expect to see `this.tandem = tandem` in several places based on that investigation.  They should all be cleaned up as described in my preceding comment.
