### ISSUE TITLE
Is the 1.0 branch still needed?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/charges-and-fields#93]
I was somewhat surprised to find a branch called "1.0" during a code review (#92). Should it be kept for posterity? If so, will it cause confusion when the "real" 1.0 is released?

**Comment by ariel-phet** [comment]
@andrewadare please confer with the other developers on this (at dev meeting if necessary but on the skype channel preferably). I would think it should be removed, since 1.0 should not exist until we publish.

**Comment by andrewadare** [comment]
Conclusion after discussion with dev team: keep the 1.0 branch and merge master into it when ready. There may be GitHub issues tied to that branch that should be preserved.

Indirectly related: the existing RC versions and testing matrix files will also be preserved, and the "real" 1.0 release candidate versioning will increment from the latest.
