### ISSUE TITLE
Make Credits alphabetical by last name

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#94]
@andrewadare can you do this? Noticed in 1.0.0-dev.19 for phetsims/tasks/issues/685.

**Comment by andrewadare** [comment]
Sure, wasn't sure about the protocol there, but that works in my favor :)

**Comment by phet-steele** [comment]
Mine, too 😆

**Comment by phet-steele** [comment]
Thanks for the quick fix!
