### ISSUE TITLE
Sensors jump to the center of the play area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#95]
@andrewadare I cannot currently test 1.0.0-dev.19 adequately. The two issues to verify as fixed are related to sensors (#88 & #89), but sensors behave incorrectly. When trying to grab a sensor from the tool box, they are instead placed in the center of the screen. Furthermore, they do not update until they are grabbed and released in the play area by the user:

![caf08](https://cloud.githubusercontent.com/assets/5863899/17938873/0f978b96-69e5-11e6-8047-114e3accf327.gif)

Seen on OSX 10.11.6 Chrome, Win 10 Edge. For phetsims/tasks/issues/685.
Troubleshooting information:
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-dev.19/charges-and-fields_en.html
Version: 1.0.0-dev.19 2016-08-23 20:28:27 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Language: en-US
Window: 1920x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1fd91832","branch":"master"},"babel":{"sha":"5e625a61","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"charges-and-fields":{"sha":"df4442b2","branch":"master"},"chipper":{"sha":"136b1d30","branch":"master"},"dot":{"sha":"6e8a26f2","branch":"master"},"joist":{"sha":"9c50d3f7","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"0ab22ac3","branch":"master"},"scenery-phet":{"sha":"a1361fa4","branch":"master"},"sherpa":{"sha":"5ddfccd4","branch":"master"},"sun":{"sha":"093126ce","branch":"master"},"tandem":{"sha":"43ebdfb3","branch":"master"}}

**Comment by andrewadare** [comment]
Argh. Traced to 8ff268d. Reverting....

**Comment by phet-steele** [comment]
The jumping and updating is indeed fixed, closing.
