### ISSUE TITLE
Items to include in teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/charges-and-fields#97]
1. From an unfuddle ticket:

> When plotting the potential for a charge distribution, a legend indicating at least qualitatively what the color scale means [red= high V, white = 0, blue = low] would be helpful. Interpreting a plot like that isn't intuitive for students new to electrostatics.

I think the current plot is quite easy to interpret, but we might make something akin to a legend or description in the teacher tips/primer
1. A comment on the the "direction" only feature would likely be useful
2. A comment on the the field representation would be good (brightness mapping to strength, even though fairly obvious), we might say a brief comment of _why_ we chose this somewhat unorthodox representation (and a good opportunity to discuss the pros/cons of such a representation with the class). Especially since many representations of the field exist, it can be useful to explore why different representations are used (arrows vs field lines for instance)
3. We might want to explicitly state something about this being purely electrostatics, and that charges are assume to be "pinned" wherever they are placed.

**Comment by ariel-phet** [comment]
@arouinfar @andrewadare @phet-steele any other items you feel should be covered/mentioned?

**Comment by ariel-phet** [comment]
1. We should also point out that the grid is arranged such that when charges are placed on the major intersections of the grid the field of a single charge will look "like the textbook" 

Notice the field points radially outward in this case

![point charge](https://cloud.githubusercontent.com/assets/4051174/18064124/357fb612-6deb-11e6-8609-2b6ebd21247e.PNG)

Whereas if not on the grid, the field (though correct) might look a bit odd at first glance

![point charge 2](https://cloud.githubusercontent.com/assets/4051174/18064145/54710580-6deb-11e6-9ddb-70f098c5ada1.PNG)

**Comment by arouinfar** [comment]
These are excellent suggestions @ariel-phet. I cross-referenced the Flash Teacher Tips and found this 

>  The E Field sensors are like the like the puck from the <i>Field Hockey</i>, but it measures like the electroscope rather than responding with motion.

While I wouldn't copy and paste this statement into the HTML5 Teacher Tips, I think it would be helpful to add a statement about how the E-field sensors operate.

**Comment by ariel-phet** [comment]
@arouinfar - agreed

**Comment by arouinfar** [comment]
@ariel-phet what's the timeline for this? Looks like the latest dev test went smoothly, so I'm optimistic that there may be just one RC. If I have the tips ready by Friday, would that be soon enough?

**Comment by ariel-phet** [comment]
@arouinfar I think by Friday would be reasonable. Lets start gathering the other materials as well noted in the master checklist https://github.com/phetsims/charges-and-fields/issues/32

Assigning the checklist to you for the moment for the prepublication items (and to make sure interview notes are pasted into the doc, backed up and such)

**Comment by phet-steele** [comment]
Probably could state something about #46. Modelling co-located charges isn't exactly realistic; the sim WILL exhibit buggy behaviour with 3+ pairs.

**Comment by arouinfar** [comment]
Thanks @phet-steele!

**Comment by arouinfar** [comment]
Converting this list to a checklist
- [x] Describe color scale for electric potential
- [x] Direction only 
- [x] E-field representation as arrows on the grid (brightness maps to strength)
- [x] Charges are pinned
- [x] Arrangement of arrows on grid
- [x] E-field sensors
- [x] Co-locating 3+ pairs

**Comment by arouinfar** [comment]
These suggestions have all been added to the Teacher Tips. Closing.
